name: PHPStan
run-name: Run PHPStan on `${{ github.head_ref }}`

on:
  push:
    branches:
      - master
    paths:
      - composer.json
      - composer.lock
      - Plugin.php
      - includes/**
      - .github/workflows/phpstan.yml
  pull_request:
    paths:
      - composer.json
      - composer.lock
      - Plugin.php
      - includes/**
      - .github/workflows/phpstan.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Detect File Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            wpcontent:
              - added|modified: 'Plugin.php'
              - added|modified: 'includes/**/*.php'

      - name: Setup PHP
        if: ${{ steps.filter.outputs.wpcontent == 'true' }}
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          ini-values: "memory_limit=1G"
          coverage: none

      - name: Validate composer.json and composer.lock
        if: ${{ steps.filter.outputs.wpcontent == 'true' }}
        run: composer validate --no-check-publish

      - name: Install Composer dependencies
        if: ${{ steps.filter.outputs.wpcontent == 'true' }}
        run: |
          composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Run PHPStan checks
        if: ${{ steps.filter.outputs.wpcontent == 'true' }}
        run: ./vendor/bin/phpstan analyse ${{ steps.filter.outputs.wpcontent_files }}