name: PHPUnit

on: workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6
        working-directory: tests

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: tests/bootstrap.php
          configuration: phpunit.xml.dist
          args: --coverage-text